apiVersion: spark.stackable.de/v1
kind: SparkApplication
metadata:
  name: spark-application
spec:
  image: "spark"
  mainApplicationFile: "target/classes/spark-3.0.1-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.0.1.jar"
  mainClass: "org.apache.spark.examples.SparkPi"
  mode: "cluster"
  driver:
    cores: "1"
    memory: "500m"
  executor:
    instances: 2
    cores: "2"
    memory: "1g"
  args:
    - "5"
