apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - selector: 
         matchLabels:
           host: "abc"
         instances: 1
    nodeName: ""
    instances: 1 # TODO: remove -> instances moved to selector
    cpu: "1"
    memory: "1G"
    # TODO: spec.containers[0].name: Invalid value: "spark:3.0.1":
    # a DNS-1123 label must consist of lowercase alphanumeric characters or '-'
    image: "spark-3-0-1-hadoop"
    command:
      - "/sbin/start-master.sh"
    args:
      - ""
  worker:
    selectors:
      - selector: 
         matchLabels:
           host: "efg"
         instances: 2
    nodeName: ""
    instances: 2 # TODO: remove -> instances moved to selector
    cpu: "2"
    memory: "2G"
    # TODO: spec.containers[0].name: Invalid value: "spark:3.0.1":
    # a DNS-1123 label must consist of lowercase alphanumeric characters or '-'
    image: "spark-3-0-1-hadoop"
    command:
      - "/sbin/start-slave.sh"
    args:
      - "<master-spark-url>" 
      - "--cores"
      - "2"
      - "--memory"
      - "2G"
  metrics: false