apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - selector: 
         matchLabels:
           kubernetes.io/hostname: "bawa-virtualbox"
    instances: 2
    cpu: "1"
    memory: "500m"
    command:
      - "spark-3.0.1-bin-hadoop2.7/sbin/start-master.sh"
    env:
#      - name: SPARK_HOME
#        value: "{{packageroot}}/spark-3.0.1-bin-hadoop2.7"
#      - name: SPARK_CONF_DIR
#        value: "{{configroot}}"
      - name: "SPARK_NO_DAEMONIZE"
        value: "true"
  worker:
    selectors:
      - selector: 
         matchLabels:
           kubernetes.io/hostname: "bawa-virtualbox"
    instances: 4 
    cpu: "1"
    memory: "1000m"
    command:
      # hostname and port provided from operator: start-slave.sh <MASTER_URL:MASTER_PORT>
      - "spark-3.0.1-bin-hadoop2.7/sbin/start-slave.sh"
    env:
#      - name: SPARK_HOME
#        value: "{{packageroot}}/spark-3.0.1-bin-hadoop2.7"
#      - name: SPARK_CONF_DIR
#        value: "{{configroot}}"
      - name: "SPARK_NO_DAEMONIZE"
        value: "true"
  image: "spark:3.0.1"
  metrics: false
