apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - selector: 
         matchLabels:
           kubernetes.io/hostname: "bawa-virtualbox"
    instances: 1
    cpu: "1"
    memory: "500m"
    command:
      - "sbin/start-master.sh"
    env:
#      - name: SPARK_HOME
#        value: "{{packageroot}}"
#      - name: SPARK_CONF_DIR
#        value: "{{configroot}}"
      - name: "SPARK_NO_DAEMONIZE"
        value: "true"
  worker:
    selectors:
      - selector: 
         matchLabels:
           kubernetes.io/hostname: "bawa-virtualbox"
    instances: 0 
    cpu: "1"
    memory: "1000m"
    command:
      - "sbin/start-slave.sh"
      - "spark://bawa-virtualbox:7077"
    env:
#      - name: SPARK_HOME
#        value: "{{packageroot}}"
#      - name: SPARK_CONF_DIR
#        value: "{{configroot}}"
      - name: "SPARK_NO_DAEMONIZE"
        value: "true"
  image: "spark:3.0.1"
  metrics: false
