apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - selector: 
         matchLabels:
           host: "abc"
         instances: 2
    nodeName: ""
    instances: 2 # TODO: remove -> instances moved to selector
    cpu: "100"
    memory: "1GB"
    image: busybox
    command:
      - "sleep"
    args:
      - "3600"
  worker:
    selectors:
      - selector: 
         matchLabels:
           host: "efg"
         instances: 4
    nodeName: ""
    instances: 4 # TODO: remove -> instances moved to selector
    cpu: "0.5"
    memory: "2GB"
    image: busybox
    command:
      - "sleep"
    args:
      - "3600"
  metrics: false
