apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - selector: 
         matchLabels:
           kubernetes.io/hostname: "bawa-virtualbox"
    instances: 1
    cpu: "1"
    memory: "1G"
    command:
      - "sbin/start-master.sh"
    env:
      - name: SPARK_HOME
        value: "{{packageroot}}"
      - name: SPARK_CONF_DIR
        value: "{{configroot}}"
  worker:
    selectors:
      - selector: 
         matchLabels:
           kubernetes.io/hostname: "bawa-virtualbox"
    instances: 2 
    cpu: "2"
    memory: "2G"
    command:
      - "sbin/start-slave.sh"
    env:
      - name: SPARK_HOME
        value: "{{packageroot}}"
      - name: SPARK_CONF_DIR
        value: "{{configroot}}"
  image: "spark:3.0.1"
  metrics: false
