apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    instances: 2
    cpu: "200"
    memory: "2GB"
    command:
      - "sleep"
    args:
      - "3600"
    image: busybox
  worker:
    instances: 4
    cpu: "1.0"
    memory: "3GB"
    command:
      - "sleep"
    args:
      - "3600"
    image: busybox
  metrics: false
  sparkWebUI: false
  sparkConfigurationMap: noMap""
  sparkConfiguration:
    - "no Config"
  env:
    - "no Env"
