apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    instances: 1
    cpu: "100"
    memory: "1GB"
    image: busybox
    command:
      - "sleep"
    args:
      - "3600"
  worker:
    instances: 2
    cpu: "0.5"
    memory: "2GB"
    image: busybox
    command:
      - "sleep"
    args:
      - "3600"
  metrics: false
