apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    instances: 2
    cpu: "200"
    memory: "2GB"
    image: busybox
    command:
      - "sleep"
    args:
      - "3600"
  worker:
    instances: 4
    cpu: "1.0"
    memory: "3GB"
    image: busybox
    command:
      - "sleep"
    args:
      - "3600"
  metrics: false
